version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "translate-all-documents"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mhzjm1gn6clf"
s3_prefix = "translate-all"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "NumberOfIteration=\"30\""

